### ISSUE TITLE
 Quizzes are not properly downloaded

### ISSUE THREAD

**Issue by daniarla** [C0D3D3V/Moodle-DL#213]
## Description of the bug

When you download a quiz the some parts of the html are changed via moodle_constants.py. Some of the links are not valid any more (I tried manually visiting the sites) or not accessible to non uni students, and some parts of the UI are missing. 

## Steps to reproduce the issue

Download a quiz from moodle.
![quizz](https://github.com/C0D3D3V/Moodle-DL/assets/80422846/b45a089e-1293-49b4-bbaa-22df7d79987b)

## Possible Fix

Don't hard-code the links to a specific uni or link? I get why you did it and I thought of using a public facing moodle instance like school.moodledemo.net but at some point probably the links will stop working.  

The best thing that I can thing right now is downloading the script that the page is using and storing it alongside the html.
And if that is not possible maybe stripping all the decoration and going with a super simple plain html with the right information.

This is a suuuper low priority bug as you can tell what was right and wrong despite some parts missing. 

Thanks for your amazing work as always!

**Comment by C0D3D3V** [comment]
For me the quizzes still locks fine. (only some resources are missing, but not the font that is missing in your image) Maybe your browser does not allow cros origin requests.  You can send me your HTML if you want. Maybe try to open your HTML in Chrome since it has less strict CROS rules than Firefox.

Yes, I used the moodle of RUB because it is a big University in Germany and I guess they will leave the moodle for long time on that domain. It was the simplest option for me, because creating an own styling or copying the styling of moodle app is a lot of work. 

We have some options:
- update to the new styling of RUB moodle so there are no more missing resources. 
- host the missing resources on github, change the href to github
- copy the style of moodle mobile app, and embedd every needed resource using base64
- create an own styling that does not use any online resources so that you can view everything also offline

**Comment by C0D3D3V** [comment]
* correcting myself - even the flag image is shown, that is part of the downloaded quiz and is included via href -> my testing moodle instance was only down, thats why it was not shown.

So for me everything is still correctly displayed :D 

But I would also love to have a clean simple own CSS.

**Comment by C0D3D3V** [comment]
And strict cross origin is a problem indeed. A clean css where everything is included in the HTML would be the best.

**Comment by C0D3D3V** [comment]
For the record. The moodle mobile app uses these ionic angular templates to build the html:
 
https://github.com/moodlehq/moodleapp/blob/97856e457a84d9b74bd320def97715b75eedc5ce/src/addons/mod/quiz/pages/review/review.html
https://github.com/moodlehq/moodleapp/blob/97856e457a84d9b74bd320def97715b75eedc5ce/src/core/features/question/components/question/core-question.html

(and some more, see the source)

And the question helper contains most functions to build the Components, and extract and build the needed js
https://github.com/moodlehq/moodleapp/blob/97856e457a84d9b74bd320def97715b75eedc5ce/src/core/features/question/services/question-helper.ts
https://github.com/moodlehq/moodleapp/blob/97856e457a84d9b74bd320def97715b75eedc5ce/src/core/features/question/classes/base-question-component.ts#L454

Also there are many more questiontypes... 
https://github.com/moodlehq/moodleapp/blob/97856e457a84d9b74bd320def97715b75eedc5ce/src/addons/qtype/qtype.module.ts

I do not think it is a good Idea to copy all this into moodle-dl or even to call the ionic from python to generate the html. Thats seems out of scope for moodle-dl



Also this indicates how complicated it would be to build an own styling.


I will think about a solution that could work, with minimal effort.

**Comment by daniarla** [comment]
> So for me everything is still correctly displayed :D

![fyc](https://github.com/C0D3D3V/Moodle-DL/assets/80422846/96578564-36a4-413f-8454-58c95be1f330)

For me it does not matter what browser I use I can not get all the images.


> I will think about a solution that could work, with minimal effort.

Maybe the simple solution is not using an html at all? I can live with simple markdown file as long as I can get all the info.


> Also there are many more questiontypes...

Yeah.... Seems like a lot of work to implement something for each one :(

**Comment by C0D3D3V** [comment]
Simplest solution for now is, to include the css into the HTML, and fix the font by using a CDN or import it with base64 (so you could also view it without internet).

And we do not care about all the javascript problems for now until someone finds a new problem :D 

We can not use some other moodle instance since now all moodle instance on latest version use the same side cross origin, (we could only use an outdated instance, but somday it will be updated) and do no longer allow cross origin from other domains (like local) . 

P.S. Creating a good readable markdown is not that simple. Its as readable as if you remove the Style from the HTML, and you will not see the question correctly, since we can not display checkboxes and other stuff, like textboxes, drag and drob questions.....

I would stick with HTML, but fix it somehow.

**Comment by daniarla** [comment]
> P.S. Creating a good readable markdown is not that simple. Its as readable as if you remove the Style from the HTML, and you will not see the question correctly, since we can not display checkboxes and other stuff, like textboxes, drag and drob questions.....

I didn't think about that, makes sense.



> I would stick with HTML, but fix it somehow.

Good call. :+1:

**Comment by C0D3D3V** [comment]
[Fixed Quizz Header And Footer.zip](https://github.com/C0D3D3V/Moodle-DL/files/15039903/Fixed.Quizz.Header.And.Footer.zip)

I pin this file here just that I can find it if we need it in the future.

I will solve the problem for now, just by fixing the font problem. (that will only add like 10 lines to the html)
Fixing all other problems, (that may already exists, but we cant tell. because we have no test data) we will do on demand. For that we probably need to include all the files as I did in the uploaded `Fixed Quizz Header And Footer.html`

**Comment by C0D3D3V** [comment]
Please test the latest version, if you have more problems with Quizzes HTMLs, please report them in new issues.
